# Generated by Django 4.1.2 on 2024-06-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id_nav', models.AutoField(db_column='idNav', primary_key=True, serialize=False)),
                ('nombre_nav', models.CharField(max_length=25)),
            ],
        ),
    ]
