# Generated by Django 4.1.2 on 2024-06-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='id_nav',
            field=models.CharField(db_column='idNav', max_length=25, primary_key=True, serialize=False),
        ),
    ]
