# Generated by Django 4.1.2 on 2024-07-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_navbar_id_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quienes',
            fields=[
                ('id_quienes', models.CharField(db_column='idQuienes', max_length=25, primary_key=True, serialize=False)),
                ('descripcion_quienes', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicios', models.AutoField(db_column='idServicios', primary_key=True, serialize=False)),
                ('titulo_servicios', models.CharField(max_length=25)),
                ('descripcion_servicios', models.TextField()),
                ('imagen_servicios', models.ImageField(upload_to='img/servicios/')),
            ],
        ),
    ]
