# Generated by Django 4.1.2 on 2024-07-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_quienes_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienes',
            name='titulo_quienes',
            field=models.CharField(default='Default', max_length=25),
        ),
        migrations.AlterField(
            model_name='quienes',
            name='descripcion_quienes',
            field=models.TextField(),
        ),
    ]
