# Generated by Django 4.1.2 on 2024-07-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_quienes_titulo_quienes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='titulo_servicios',
            field=models.CharField(max_length=70),
        ),
    ]
